version: '2.2'
services:
  grafana:
    image: grafana/grafana:6.6.0
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=doitintl-bigquery-datasource,https://github.com/kernelci/grafana-singlevalue-panel/releases/download/2.0.0/grafana-singlevalue-panel-2.0.0.zip;grafana-singlevalue-panel
      - GF_SERVER_DOMAIN=staging.kernelci.org
      - GF_SERVER_HTTP_PORT=3000
      - GF_AUTH_ANONYMOUS_ENABLED=true

volumes:
  grafana-storage:
  
