{
 "title": "Branch",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataset", "query": "kcidb_sample" },
   {
    "name": "git_repository_url",
    "label": "Repository URL",
    "query": "SELECT DISTINCT git_repository_url FROM ${dataset}.checkouts"
   },
   {
    "name": "git_repository_branch",
    "label": "Name",
    "query": "SELECT DISTINCT git_repository_branch FROM ${dataset}.checkouts WHERE git_repository_url = ${git_repository_url:json}"
   },
   {
    "name": "origin",
    "label": "Origin",
    "query": "SELECT DISTINCT origin FROM ${dataset}.checkouts"
   },
   {
    "name": "build_architecture",
    "label": "Build architecture",
    "query": "SELECT DISTINCT architecture FROM ${dataset}.builds"
   },
   {
    "name": "build_config_name",
    "label": "Build configuration",
    "query": "SELECT DISTINCT config_name FROM ${dataset}.builds"
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "targets": [
    { "panelId": 12 }
   ]
  },
  { "type": "grafana-singlevalue-panel", "gridPos": { "h": 2, "w": 19, "x": 5, "y": 0 } },
  {
   "title": "Origins",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    STRING_AGG(DISTINCT origin, \", \" ORDER BY origin ASC) AS origins,\n    ${git_repository_url:json} AS git_repository_url,\n    ${git_repository_branch:json} AS git_repository_branch\nFROM ${dataset}.checkouts\nWHERE\n    start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n    git_repository_url=${git_repository_url:json} AND\n    git_repository_branch=${git_repository_branch:json} AND\n    origin LIKE ${origin}"
    }
   ]
  },
  {
   "title": "Repository URL",
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 11, "x": 8, "y": 2 },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Revisions",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "/*\n * Truncate a string with an ellipsis at speсified length.\n */\nCREATE TEMP FUNCTION TRUNCATE(str STRING, len INT64)\n    RETURNS STRING\n    AS (IF(len = 0 OR CHAR_LENGTH(str) <= len,\n           str,\n           CONCAT(SUBSTR(str, 1, len - 1), \"…\")\n       ));\n\n/*\n * Replace NULL or empty string with a non-breaking space,\n * truncate anything else with ellipsis, if necessary.\n */\nCREATE TEMP FUNCTION BLANK_OR_TRUNCATE(str STRING, len INT64)\n    RETURNS STRING\n    AS (IF(str IS NULL OR str = \"\", \" \", TRUNCATE(str, len)));\n\n/*\n * Format an array of strings as a three-line text with ellipsis\n */\nCREATE TEMP FUNCTION ARRAY_TO_TEXT(strs ARRAY<STRING>, width INT64)\n    RETURNS STRING\n    AS (ARRAY_TO_STRING(\n        [\n            BLANK_OR_TRUNCATE(strs[SAFE_OFFSET(0)], width),\n            BLANK_OR_TRUNCATE(strs[SAFE_OFFSET(1)], width),\n            IF(ARRAY_LENGTH(strs) > 3, \"…\",\n               BLANK_OR_TRUNCATE(strs[SAFE_OFFSET(2)], width))\n        ],\n        \"\\n\"\n    ));\n\nWITH\n    prefiltered_checkouts AS (\n        SELECT\n            *\n        FROM\n            ${dataset}.checkouts\n        WHERE\n            IFNULL(checkouts.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to), TRUE) AND\n            origin LIKE ${origin}\n    ),\n    filtered_checkouts AS (\n        SELECT\n            checkouts.*\n        FROM\n            prefiltered_checkouts AS checkouts,\n            prefiltered_checkouts AS other_checkouts\n        WHERE\n            other_checkouts.git_repository_url = ${git_repository_url:json} AND\n            other_checkouts.git_repository_branch = ${git_repository_branch:json} AND\n            checkouts.git_commit_hash = other_checkouts.git_commit_hash AND\n            checkouts.patchset_hash = other_checkouts.patchset_hash\n    ),\n    revision_sources AS (\n        SELECT\n            git_commit_hash,\n            patchset_hash,\n            ARRAY_TO_TEXT(\n                ARRAY_AGG(git_repository_url_str\n                          ORDER BY rank DESC, git_repository_url_str,\n                                   git_repository_branch_str, git_commit_name_str),\n                128\n            ) AS git_repository_urls_text,\n            ARRAY_TO_TEXT(\n                ARRAY_AGG(git_repository_branch_str\n                          ORDER BY rank DESC, git_repository_url_str,\n                                   git_repository_branch_str, git_commit_name_str),\n                32\n            ) AS git_repository_branches_text,\n            ARRAY_TO_TEXT(\n                ARRAY_AGG(git_commit_name_str\n                          ORDER BY rank DESC, git_repository_url_str,\n                                   git_repository_branch_str, git_commit_name_str),\n                32\n            ) AS git_commit_names_text,\n        FROM (\n            SELECT\n                git_commit_hash,\n                patchset_hash,\n                git_repository_url_str,\n                git_repository_branch_str,\n                git_commit_name_str,\n                IF(git_repository_url_str = \"\", 0, 4) +\n                    IF(git_repository_branch_str = \"\", 0, 2) +\n                    IF(git_commit_name_str = \"\", 0, 1) AS rank\n            FROM (\n                SELECT DISTINCT\n                    git_commit_hash,\n                    patchset_hash,\n                    IFNULL(git_repository_url, \"\") AS git_repository_url_str,\n                    IFNULL(git_repository_branch, \"\") AS git_repository_branch_str,\n                    IFNULL(git_commit_name, \"\") AS git_commit_name_str,\n                FROM\n                    filtered_checkouts\n            )\n        )\n        GROUP BY\n            git_commit_hash,\n            patchset_hash\n    )\n/* Massage and join with sources */\nSELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    revisions.git_commit_hash,\n    revisions.patchset_hash,\n    origins_str,\n    SUBSTR(revisions.git_commit_hash, 0, 12) AS git_commit_hash_short,\n    revision_sources.git_repository_urls_text,\n    revision_sources.git_repository_branches_text,\n    revision_sources.git_commit_names_text,\n    SUBSTR(revisions.patchset_hash, 0, 12) AS patchset_hash_short,\n    IFNULL(CAST(checkouts_start_time AS STRING), \"\") AS checkouts_start_time_str,\n    checkouts_valid_num,\n    builds_valid_num,\n    tests_status_num\nFROM (\n    /* Calculate revision statuses */\n    SELECT\n        checkouts.git_commit_hash,\n        checkouts.patchset_hash,\n        STRING_AGG(DISTINCT checkouts.origin, \", \") AS origins_str,\n        MIN(checkouts.start_time) AS checkouts_start_time,\n        MAX(CASE checkouts.valid WHEN false THEN 1 WHEN true THEN 0 ELSE -1 END) AS checkouts_valid_num,\n        MAX(CASE builds.valid WHEN false THEN 1 WHEN true THEN 0 ELSE -1 END) AS builds_valid_num,\n        MAX((CASE tests.status WHEN \"ERROR\" THEN 5 WHEN \"FAIL\" THEN 4 WHEN \"PASS\" THEN 3 WHEN \"DONE\" THEN 2 WHEN \"SKIP\" THEN 1 ELSE 0 END) -\n            (CASE tests.waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6) AS tests_status_num\n    FROM\n        filtered_checkouts AS checkouts\n    LEFT OUTER JOIN\n        ${dataset}.builds AS builds\n        ON\n            builds.checkout_id = checkouts.id AND\n            IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n            IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\n    LEFT OUTER JOIN\n        ${dataset}.tests AS tests\n        ON\n            tests.build_id = builds.id\n    GROUP BY\n        checkouts.git_commit_hash,\n        checkouts.patchset_hash\n) AS revisions\nINNER JOIN\n    revision_sources\n    ON\n        revision_sources.git_commit_hash = revisions.git_commit_hash AND\n        revision_sources.patchset_hash = revisions.patchset_hash\nORDER BY\n    checkouts_start_time DESC"
    }
   ]
  },
  {
   "title": "Build status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n)\nSELECT\n    interval_start AS time,\n    IF(builds.valid IS NULL, \"UNKNOWN\", IF(builds.valid, \"PASS\", \"FAIL\")) AS metric,\n    COUNT(DISTINCT builds.id) AS Builds\nFROM ${dataset}.checkouts AS checkouts, ${dataset}.builds AS builds\nINNER JOIN intervals ON builds.start_time >= interval_start AND builds.start_time < interval_end\nWHERE\n  builds.checkout_id = checkouts.id AND\n  checkouts.git_repository_url = ${git_repository_url:json} AND\n  checkouts.git_repository_branch = ${git_repository_branch:json} AND\n  builds.origin LIKE ${origin} AND\n  IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n  IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nGROUP BY time, metric\nORDER BY time ASC, metric ASC"
    }
   ]
  },
  {
   "title": "Test status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n)\nSELECT\n  interval_start AS time,\n  IF(tests.status IS NULL, \"UNKNOWN\", tests.status) AS metric,\n  COUNT(DISTINCT tests.id) AS tests\nFROM\n  ${dataset}.checkouts AS checkouts, ${dataset}.builds AS builds, ${dataset}.tests AS tests\nINNER JOIN intervals ON tests.start_time >= interval_start AND tests.start_time < interval_end\nWHERE\n  checkouts.id = builds.checkout_id AND\n  checkouts.git_repository_url = ${git_repository_url:json} AND\n  checkouts.git_repository_branch = ${git_repository_branch:json} AND\n  builds.id = tests.build_id AND\n  NOT tests.waived AND\n  tests.origin LIKE ${origin} AND\n  IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n  IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nGROUP BY\n  time, metric\nORDER BY\n  time ASC, metric ASC"
    }
   ]
  },
  {
   "title": "Reports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n), filtered_checkouts AS (\n    SELECT\n        checkouts.id AS id,\n        checkouts.origin AS origin,\n        checkouts.start_time AS time\n    FROM\n        ${dataset}.checkouts AS checkouts\n    WHERE\n      \tcheckouts.start_time BETWEEN TIMESTAMP_MILLIS ($__from) AND TIMESTAMP_MILLIS ($__to) AND\n        checkouts.git_repository_url = ${git_repository_url:json} AND\n        checkouts.git_repository_branch = ${git_repository_branch:json}\n), filtered_builds AS (\n    SELECT\n        builds.id AS id,\n        builds.origin AS origin,\n        builds.start_time AS time\n    FROM\n        ${dataset}.builds AS builds,\n        filtered_checkouts\n    WHERE\n    \tbuilds.start_time BETWEEN TIMESTAMP_MILLIS ($__from) AND TIMESTAMP_MILLIS ($__to) AND\n        IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n        IFNULL(builds.config_name LIKE ${build_config_name}, TRUE) AND\n        filtered_checkouts.id = builds.checkout_id\n), filtered_tests AS (\n    SELECT\n        tests.id AS id,\n        tests.origin AS origin,\n        tests.start_time AS time\n    FROM\n        ${dataset}.tests AS tests,\n        filtered_builds\n    WHERE\n    \ttests.start_time BETWEEN TIMESTAMP_MILLIS ($__from) AND TIMESTAMP_MILLIS ($__to) AND\n        filtered_builds.id = tests.build_id\n)\nSELECT\n    interval_start AS time,\n    counted_checkouts.count AS Checkouts,\n    counted_builds.count AS Builds,\n    counted_tests.count AS Tests\nFROM intervals\nLEFT OUTER JOIN (\n    SELECT interval_start, COUNT(id) AS count,\n    FROM filtered_checkouts\n    INNER JOIN intervals ON time >= interval_start AND time < interval_end\n    WHERE origin LIKE ${origin}\n    GROUP BY interval_start\n) AS counted_checkouts USING(interval_start)\nLEFT OUTER JOIN (\n    SELECT interval_start, COUNT(id) AS count,\n    FROM filtered_builds\n    INNER JOIN intervals ON time >= interval_start AND time < interval_end\n    WHERE origin LIKE ${origin}\n    GROUP BY interval_start\n) AS counted_builds USING(interval_start)\nLEFT OUTER JOIN (\n    SELECT interval_start, COUNT(id) AS count,\n    FROM filtered_tests\n    INNER JOIN intervals ON time >= interval_start AND time < interval_end\n    WHERE origin LIKE ${origin}\n    GROUP BY interval_start\n) AS counted_tests USING(interval_start)"
    }
   ]
  },
  {
   "title": "Builds per architecture",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "kcidb_sample",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "kernelci",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n)\nSELECT\n  interval_start AS time,\n  builds.architecture AS metric,\n  COUNT(DISTINCT builds.id) AS Builds\nFROM\n  ${dataset}.builds AS builds,\n  ${dataset}.checkouts AS checkouts\nJOIN intervals ON builds.start_time >= interval_start AND builds.start_time < interval_end\nWHERE\n  checkouts.id = builds.checkout_id AND\n  checkouts.git_repository_url = ${git_repository_url:json} AND\n  checkouts.git_repository_branch = ${git_repository_branch:json} AND\n  builds.origin LIKE ${origin} AND\n  builds.architecture LIKE ${build_architecture} AND\n  IFNULL(builds.config_name LIKE ${build_config_name}, TRUE) AND\n  builds.start_time IS NOT NULL AND\n  builds.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)\nGROUP BY\n  time, metric\nORDER BY\n  time ASC, metric ASC"
    }
   ]
  }
 ]
}