{
 "title": "Build",
 "time": { "from": "now-100y", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Database", "query": "postgres" },
   {
    "name": "id",
    "label": "ID",
    "query": "kernelci:kernelci.org:66335673be639ec87f4c42ea"
   },
   {
    "name": "origin",
    "label": "Origin",
    "query": "SELECT DISTINCT origin FROM checkouts"
   },
   {
    "name": "build_architecture",
    "label": "Build architecture",
    "query": "SELECT DISTINCT architecture FROM builds"
   },
   {
    "name": "build_config_name",
    "label": "Build configuration",
    "query": "SELECT DISTINCT config_name FROM builds"
   },
   { "name": "test_path" }
  ]
 },
 "panels": [
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  { "type": "grafana-singlevalue-panel", "gridPos": { "h": 2, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Origin",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN $origin = '%' THEN 'All'\n        ELSE $origin\n    END AS origin_param,\n    CASE\n        WHEN $build_architecture = '%' THEN 'All'\n        ELSE $build_architecture\n    END AS build_architecture_param,\n    CASE\n        WHEN $build_config_name = '%' THEN 'All'\n        ELSE $build_config_name\n    END AS build_config_name_param,\n    builds.checkout_id,\n    builds.id,\n    builds.origin,\n    builds.comment,\n    builds.architecture,\n    COALESCE(builds.config_name, 'unnamed') AS config_name,\n    COALESCE(format_cached_url(builds.config_url), '') AS config_url,\n    COALESCE(CAST(builds.start_time AS TEXT), '') AS start_time_str,\n    COALESCE(\n        TO_CHAR(builds.duration * INTERVAL '1 second', 'HH24:MI:SS.MS'),\n        ''\n    ) AS duration_str,\n    CASE \n        WHEN builds.valid = false THEN 1 \n        WHEN builds.valid = true THEN 0 \n        ELSE -1 \n    END AS valid_num,\n    CASE \n        WHEN builds.log_url IS NULL THEN '' \n        ELSE 'File' \n    END as log_url_text,\n    format_cached_url(builds.log_url),\n    builds.compiler,\n    builds.command,\n    checkouts.git_commit_hash,\n    checkouts.patchset_hash,\n    builds.misc,\n    tests.status_num AS tests_status_num\nFROM builds\nLEFT OUTER JOIN checkouts\n    ON checkouts.id = builds.checkout_id\nLEFT OUTER JOIN (\n    SELECT\n        MAX(COALESCE(array_position(ARRAY['SKIP', 'DONE', 'PASS', 'MISS', 'ERROR', 'FAIL'], tests.status::text), 0) - COALESCE(tests.waived::int, 2) * 7) AS status_num\n    FROM tests\n    WHERE\n        build_id = '$id' AND\n        COALESCE(start_time BETWEEN TO_TIMESTAMP($__from / 1000) AND TO_TIMESTAMP($__to / 1000), TRUE) AND\n        origin LIKE ${origin}\n) AS tests ON TRUE\nWHERE builds.id = '$id'"
    }
   ]
  },
  {
   "title": "Comment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Output files",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n    output_file ->> 'name' AS name,\n    format_cached_url(output_file ->> 'url') AS url\nFROM\n    builds,\n    jsonb_array_elements(builds.output_files) AS output_file\nWHERE\n    builds.id = '$id'"
    }
   ]
  },
  {
   "title": "Log",
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Tests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Architecture",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Configuration",
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Command",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Compiler",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Log excerpt",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n    (TIMESTAMP $__timeFrom() + (ordinality * interval '1 second')) AS time,\n    line AS message\nFROM\n    unnest(string_to_array((\n        SELECT\n            regexp_replace(regexp_replace(log_excerpt, '([^ ]) ', E'\\\\1​ '), ' ', ' ​') AS solid_log_excerpt\n        FROM\n            builds\n        WHERE\n            id = '$id'\n    ), E'\\n')) WITH ORDINALITY AS lines(line, ordinality)"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 2 }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "title": "Node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE WHEN '$test_path' = '' THEN 'Root' ELSE '$test_path' END AS node_title,\n    CASE WHEN '$test_path' = '' THEN '' ELSE '⮌ Parent' END AS node_parent_title,\n    CASE\n        WHEN POSITION('.' IN '$test_path') = 0 THEN ''\n        ELSE SUBSTRING('$test_path' FROM 1 FOR LENGTH('$test_path') - POSITION('.' IN REVERSE('$test_path')))\n    END AS node_parent_path,\n    CASE WHEN '$test_path' = '' THEN '' ELSE '⮌ Root' END AS node_root_title,\n    CASE WHEN $origin = '%' THEN 'All' ELSE $origin END AS origin_param,\n    CASE WHEN $build_architecture = '%' THEN 'All' ELSE $build_architecture END AS build_architecture_param,\n    CASE WHEN $build_config_name = '%' THEN 'All' ELSE $build_config_name END AS build_config_name_param"
    }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 29 },
   "targets": [
    { "panelId": 39 }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 18, "x": 4, "y": 29 },
   "targets": [
    { "panelId": 39 }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 29 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "panelId": 47 }
   ]
  },
  {
   "title": "Subnodes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "/* Massage */\nSELECT\n    CASE WHEN $origin = '%' THEN 'All' ELSE $origin END AS origin_param,\n    CASE WHEN $build_architecture = '%' THEN 'All' ELSE $build_architecture END AS build_architecture_param,\n    CASE WHEN $build_config_name = '%' THEN 'All' ELSE $build_config_name END AS build_config_name_param,\n    origins,\n    path,\n    CASE\n        WHEN '$test_path' = '' THEN path\n        ELSE substring(path FROM length('$test_path') + 2)\n    END AS name,\n    tests,\n    COALESCE(CAST(min_start_time AS TEXT), '') AS min_start_time_str,\n    COALESCE(\n        FLOOR(EXTRACT(epoch FROM AGE(max_end_time, min_start_time))/3600) ||\n        TO_CHAR(AGE(max_end_time, min_start_time), ':MI:SS.MS'),\n        ''\n    ) AS total_duration_str,\n    status_num\nFROM (\n    /* Aggregate */\n    SELECT\n        STRING_AGG(DISTINCT origin, ', ') AS origins,\n        LEFT(base_prefix, CHAR_LENGTH(base_prefix) - 1) AS path,\n        MIN(start_time) AS min_start_time,\n        MAX(end_time) AS max_end_time,\n        COUNT(DISTINCT id) AS tests,\n        MAX(COALESCE(array_position(ARRAY['SKIP', 'DONE', 'PASS', 'MISS', 'ERROR', 'FAIL'], status::text), 0) - COALESCE(waived::int, 2) * 7) AS status_num\n    FROM (\n        /* Filter tests and extract path prefixes */\n        SELECT\n            tests.origin,\n            tests.id,\n            /*\n             * Prefix one level deeper than the displayed test's path,\n             * i.e. the prefix children of this test should have\n             */\n            COALESCE(\n                /*\n                 * Handle the parent node of this test being displayed:\n                 * cut the test path up to and including the first dot\n                 * after the currently-displayed test's path, if possible.\n                 */\n                LEFT(\n                    tests.path,\n                    LENGTH('$test_path') +\n                    NULLIF(POSITION('.' IN SUBSTRING(tests.path FROM LENGTH('$test_path') + 2)), 0) +\n                    1\n                ),\n                /* Handle this test's node being displayed */\n                tests.path || '.'\n            ) AS base_prefix,\n            tests.start_time,\n            tests.start_time + (tests.duration * INTERVAL '1 second') AS end_time,\n            tests.status,\n            tests.waived\n        FROM tests\n        WHERE\n            tests.build_id = '$id' AND\n            COALESCE(tests.start_time BETWEEN TO_TIMESTAMP($__from / 1000) AND TO_TIMESTAMP($__to / 1000), TRUE) AND\n            tests.origin LIKE $origin AND\n            ('$test_path' = '' OR STARTS_WITH(tests.path, '$test_path' || '.'))\n    ) AS filtered_tests\n    GROUP BY\n        base_prefix\n) AS aggregated_tests\nORDER BY\n    status_num DESC,\n    name ASC\n"
    }
   ]
  },
  {
   "title": "Test status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    TO_TIMESTAMP(0) AS time,\n    COALESCE(tests.status::text, 'UNKNOWN') AS metric,\n    COUNT(tests.id) AS value\nFROM tests\nWHERE\n    tests.build_id = '$id' AND\n    COALESCE(tests.start_time BETWEEN TO_TIMESTAMP($__from / 1000) AND TO_TIMESTAMP($__to / 1000), TRUE) AND\n    NOT tests.waived AND\n    tests.origin LIKE $origin AND\n    ('$test_path' = '' OR tests.path = '$test_path' OR STARTS_WITH(tests.path, '$test_path' || '.'))\nGROUP BY metric\nORDER BY metric"
    }
   ]
  },
  {
   "title": "Top 5 test failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    TO_TIMESTAMP(0) AS time,\n    tests.path AS metric,\n    COUNT(tests.id) AS value\nFROM tests\nWHERE\n    tests.build_id = '$id' AND\n    COALESCE(tests.start_time BETWEEN TO_TIMESTAMP($__from / 1000) AND TO_TIMESTAMP($__to / 1000), TRUE) AND\n    NOT tests.waived AND\n    tests.status = 'FAIL' AND\n    tests.origin LIKE $origin AND\n    ('$test_path' = '' OR tests.path = '$test_path' OR STARTS_WITH(tests.path, '$test_path' || '.'))\nGROUP BY metric\nORDER BY value DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Tests",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE WHEN $origin = '%' THEN 'All' ELSE $origin END AS origin_param,\n    CASE WHEN $build_architecture = '%' THEN 'All' ELSE $build_architecture END AS build_architecture_param,\n    CASE WHEN $build_config_name = '%' THEN 'All' ELSE $build_config_name END AS build_config_name_param,\n    tests.id,\n    tests.origin,\n    tests.path,\n    tests.comment,\n    COALESCE(CAST(tests.start_time AS TEXT), '') AS start_time_str,\n    COALESCE(\n        TO_CHAR(tests.duration * INTERVAL '1 second', 'HH24:MI:SS.MS'),\n        ''\n    ) AS duration_str,\n    COALESCE(array_position(ARRAY['SKIP', 'DONE', 'PASS', 'MISS', 'ERROR', 'FAIL'], tests.status::text), 0) - COALESCE(tests.waived::int, 2) * 7 AS status_num\nFROM tests\nWHERE\n    tests.build_id = '$id' AND\n    COALESCE(start_time BETWEEN TO_TIMESTAMP($__from / 1000) AND TO_TIMESTAMP($__to / 1000), TRUE) AND\n    tests.origin LIKE $origin AND\n    ('$test_path' = '' OR tests.path = '$test_path' OR tests.path LIKE ('$test_path' || '.%'))\nORDER BY\n    status_num DESC,\n    tests.path ASC"
    }
   ]
  }
 ]
}