{
 "title": "Checkout",
 "time": { "from": "now-100y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "ID",
    "query": "_:kernelci:239d588d7e556eeef28f79a75e252e3992fb8b85"
   },
   { "name": "dataset", "query": "kcidb_sample" },
   {
    "name": "origin",
    "label": "Origin",
    "query": "SELECT DISTINCT origin FROM ${dataset}.checkouts"
   },
   {
    "name": "build_architecture",
    "label": "Build architecture",
    "query": "SELECT DISTINCT architecture FROM ${dataset}.builds"
   },
   {
    "name": "build_config_name",
    "label": "Build configuration",
    "query": "SELECT DISTINCT config_name FROM ${dataset}.builds"
   },
   { "name": "test_path" }
  ]
 },
 "panels": [
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  { "type": "grafana-singlevalue-panel", "gridPos": { "h": 2, "w": 20, "x": 4, "y": 0 } },
  {
   "title": "Origin",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "CREATE TEMPORARY FUNCTION cached_url(url STRING)\nRETURNS STRING\nLANGUAGE js AS \"\"\"\n  if (url === null) {\n    return null;\n  }\n  return \"https://us-central1-kernelci-production.cloudfunctions.net/\" +\n         \"kcidb_cache_redirect?\" + encodeURIComponent(url);\n\"\"\";\n\nSELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    id,\n    IF(log_url IS NULL, \"\", \"File\") AS log_url_text,\n    cached_url(log_url),\n    origin,\n    IFNULL(git_repository_url, \"\") AS git_repository_url,\n    IFNULL(git_repository_branch, \"\") AS git_repository_branch,\n    IFNULL(git_commit_name, \"\") AS git_commit_name,\n    IFNULL(git_commit_hash, \"\") AS git_commit_hash,\n    IFNULL(patchset_hash, \"\") AS patchset_hash,\n    CASE valid WHEN false THEN 1 WHEN true THEN 0 ELSE -1 END AS valid_num,\n    IFNULL(comment, \"\") AS comment,\n    IFNULL(CAST(start_time AS STRING), \"\") AS start_time_str,\n    misc\nFROM ${dataset}.checkouts\nWHERE id=${id:json}"
    }
   ]
  },
  {
   "title": "Repository",
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 14, "x": 2, "y": 2 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Log",
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "min",
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Builds",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Tests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Branch",
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 5, "x": 2, "y": 4 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Commit name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Commit hash",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Patches",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "orderByCol": "2",
     "orderBySort": "1",
     "rawSql": "CREATE TEMPORARY FUNCTION cached_url(url STRING)\nRETURNS STRING\nLANGUAGE js AS \"\"\"\n  if (url === null) {\n    return null;\n  }\n  return \"https://us-central1-kernelci-production.cloudfunctions.net/\" +\n         \"kcidb_cache_redirect?\" + encodeURIComponent(url);\n\"\"\";\n\n\nSELECT name, cached_url(url) AS url\nFROM UNNEST((\n    SELECT patchset_files\n    FROM ${dataset}.checkouts\n    WHERE id = ${id:json}\n))\nWITH OFFSET as idx\nORDER BY idx ASC"
    }
   ]
  },
  {
   "title": "Patchset hash",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Comment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 10 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Misc",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 20 }
   ]
  },
  { "title": "Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Builds",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    builds.id AS id,\n    builds.origin AS origin,\n    builds.architecture AS architecture,\n    REGEXP_REPLACE(builds.compiler, \"^(.{48}).+$\", \"\\\\1…\") AS compiler,\n    REGEXP_REPLACE(builds.config_name, \"^(.{48}).+$\", \"\\\\1…\") AS config_name,\n    IFNULL(CAST(builds.start_time AS STRING), \"\") AS start_time_str,\n    IFNULL(FORMAT_TIME(\"%H:%M:%E3S\", TIME_ADD(TIME \"00:00:00\", INTERVAL CAST((builds.duration * 1000) AS INT64) MILLISECOND)), \"\") AS duration_str,\n    builds.comment AS comment,\n    CASE builds.valid WHEN false THEN 1 WHEN true THEN 0 ELSE -1 END AS valid_num,\n    tests.status_num AS tests_status_num\nFROM ${dataset}.builds AS builds\nLEFT OUTER JOIN (\n    SELECT\n        build_id,\n        MAX((CASE tests.status WHEN \"ERROR\" THEN 5 WHEN \"FAIL\" THEN 4 WHEN \"PASS\" THEN 3 WHEN \"DONE\" THEN 2 WHEN \"SKIP\" THEN 1 ELSE 0 END) -\n            (CASE tests.waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6) AS status_num\n    FROM ${dataset}.tests\n    WHERE\n        start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n        origin LIKE ${origin}\n    GROUP BY build_id\n) AS tests ON tests.build_id = builds.id\nWHERE\n    checkout_id = ${id:json} AND\n    builds.origin LIKE ${origin} AND\n    builds.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n    IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n    IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nORDER BY\n    valid_num DESC,\n    tests_status_num DESC,\n    start_time ASC"
    }
   ]
  },
  {
   "title": "Build status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    TIMESTAMP_MILLIS(0) AS time,\n    IF(valid, \"PASS\", \"FAIL\") AS metric,\n    COUNT(id) AS value\nFROM ${dataset}.builds AS builds\nWHERE\n    checkout_id = ${id:json} AND\n    origin LIKE ${origin} AND\n    start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n    IFNULL(architecture LIKE ${build_architecture}, TRUE) AND\n    IFNULL(config_name LIKE ${build_config_name}, TRUE)\nGROUP BY valid\nORDER BY metric"
    }
   ]
  },
  {
   "title": "Top 10 architecture build failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    TIMESTAMP_MILLIS(0) AS time,\n    architecture AS metric,\n    COUNT(id) AS value\nFROM ${dataset}.builds AS builds\nWHERE\n    checkout_id = ${id:json} AND\n    origin LIKE ${origin} AND\n    start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n    architecture LIKE ${build_architecture} AND\n    IFNULL(config_name LIKE ${build_config_name}, TRUE) AND\n    NOT valid\nGROUP BY metric\nORDER BY value DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 5 configuration build failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    TIMESTAMP_MILLIS(0) AS time,\n    config_name AS metric,\n    COUNT(id) AS value\nFROM ${dataset}.builds AS builds\nWHERE\n    checkout_id = ${id:json} AND\n    origin LIKE ${origin} AND\n    start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n    IFNULL(architecture LIKE ${build_architecture}, TRUE) AND\n    config_name LIKE ${build_config_name} AND\n    NOT valid\nGROUP BY metric\nORDER BY value DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Top 5 compiler build failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    TIMESTAMP_MILLIS(0) AS time,\n    IF(LENGTH(compiler) > 32, CONCAT(SUBSTR(compiler, 1, 31), \"…\"), compiler) AS metric,\n    COUNT(id) AS value\nFROM ${dataset}.builds AS builds\nWHERE\n    checkout_id = ${id:json} AND\n    origin LIKE ${origin} AND\n    start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n    IFNULL(architecture LIKE ${build_architecture}, TRUE) AND\n    IFNULL(config_name LIKE ${build_config_name}, TRUE) AND\n    NOT valid AND\n    compiler IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\nLIMIT 5"
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  { "title": "Node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 47 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    IF(${test_path:json} = \"\", \"Root\", ${test_path:json}) AS node_title,\n    IF(${test_path:json} = \"\", \"\", \"⮌ Parent\") AS node_parent_title,\n    IF(\n        STRPOS(${test_path:json}, \".\") = 0,\n        \"\",\n        LEFT(${test_path:json}, CHARACTER_LENGTH(${test_path:json}) - STRPOS(REVERSE(${test_path:json}), \".\"))\n    ) AS node_parent_path,\n    IF(${test_path:json} = \"\", \"\", \"⮌ Root\") AS node_root_title,\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param"
    }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 47 },
   "targets": [
    { "panelId": 54 }
   ]
  },
  {
   "type": "grafana-singlevalue-panel",
   "gridPos": { "h": 2, "w": 18, "x": 4, "y": 47 },
   "targets": [
    { "panelId": 54 }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 47 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "panelId": 68 }
   ]
  },
  {
   "title": "Subnodes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "/* Massage */\nSELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    origins,\n    path,\n    IF(${test_path:json} = \"\", path, SUBSTR(path, CHARACTER_LENGTH(${test_path:json}) + 2)) AS name,\n    architectures,\n    tests,\n    IFNULL(CAST(min_start_time AS STRING), \"\") AS min_start_time_str,\n    IFNULL(\n        FORMAT_TIME(\n            \"%H:%M:%E3S\",\n            TIME_ADD(\n                TIME \"00:00:00\",\n                INTERVAL DATETIME_DIFF(max_end_time, min_start_time, MILLISECOND) MILLISECOND\n            )\n        ),\n        \"\"\n    ) AS total_duration_str,\n    status_num\nFROM (\n    /* Aggregate */\n    SELECT\n        STRING_AGG(DISTINCT origin, \", \") AS origins,\n        LEFT(base_prefix, CHAR_LENGTH(base_prefix) - 1) AS path,\n        STRING_AGG(DISTINCT architecture, \", \") AS architectures,\n        MIN(start_time) AS min_start_time,\n        MAX(end_time) AS max_end_time,\n        COUNT(DISTINCT id) AS tests,\n        MAX((CASE status WHEN \"ERROR\" THEN 5 WHEN \"FAIL\" THEN 4 WHEN \"PASS\" THEN 3 WHEN \"DONE\" THEN 2 WHEN \"SKIP\" THEN 1 ELSE 0 END) -\n            (CASE waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6) AS status_num\n    FROM (\n        /* Filter tests and extract path prefixes */\n        SELECT\n            tests.origin,\n            tests.id,\n            /* Prefix one level deeper than the displayed test's path */\n            IFNULL(\n                NULLIF(\n                    /*\n                     * Cut the test path up to and including the first dot\n                     * after the currently-displayed test's path\n                     */\n                    LEFT(\n                        tests.path,\n                        INSTR(tests.path, \".\", CHARACTER_LENGTH(${test_path:json}) + 2)\n                    ),\n                    \"\"\n                ),\n                tests.path || \".\"\n            ) AS base_prefix,\n            builds.architecture,\n            tests.start_time,\n            TIMESTAMP_ADD(tests.start_time, INTERVAL CAST((tests.duration * 1000) AS INT64) MILLISECOND) AS end_time,\n            tests.status,\n            tests.waived\n        FROM ${dataset}.tests\n        INNER JOIN\n            ${dataset}.builds AS builds\n            ON\n                tests.build_id = builds.id AND\n                builds.checkout_id = ${id:json} AND\n                IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n                IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\n        WHERE\n            IFNULL(tests.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to), TRUE) AND\n            tests.origin LIKE ${origin} AND\n            (${test_path:json} = \"\" OR STARTS_WITH(tests.path, ${test_path:json} || \".\"))\n    )\n    GROUP BY\n        base_prefix\n)\nORDER BY\n    status_num DESC,\n    name ASC"
    }
   ]
  },
  {
   "title": "Test status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    TIMESTAMP_MILLIS(0) AS time,\n    IFNULL(tests.status, \"UNKNOWN\") AS metric,\n    COUNT(tests.id) AS value\nFROM ${dataset}.tests\nINNER JOIN\n    ${dataset}.builds AS builds\n    ON\n        tests.build_id = builds.id AND\n        builds.checkout_id = ${id:json} AND\n        IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n        IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nWHERE\n    IFNULL(tests.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to), TRUE) AND\n    NOT tests.waived AND\n    tests.origin LIKE ${origin} AND\n    (${test_path:json} = \"\" OR tests.path = ${test_path:json} OR STARTS_WITH(tests.path, ${test_path:json} || \".\"))\nGROUP BY metric\nORDER BY metric"
    }
   ]
  },
  {
   "title": "Top 5 test failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    TIMESTAMP_MILLIS(0) AS time,\n    tests.path AS metric,\n    COUNT(tests.id) AS value\nFROM ${dataset}.tests\nINNER JOIN\n    ${dataset}.builds AS builds\n    ON\n        tests.build_id = builds.id AND\n        builds.checkout_id = ${id:json} AND\n        IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n        IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nWHERE\n    IFNULL(tests.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to), TRUE) AND\n    NOT tests.waived AND\n    tests.status = \"FAIL\" AND\n    tests.origin LIKE ${origin} AND\n    (${test_path:json} = \"\" OR tests.path = ${test_path:json} OR STARTS_WITH(tests.path, ${test_path:json} || \".\"))\nGROUP BY metric\nORDER BY value DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Tests",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    tests.id,\n    tests.origin,\n    tests.path,\n    tests.comment,\n    builds.architecture,\n    IFNULL(CAST(tests.start_time AS STRING), \"\") AS start_time_str,\n    IFNULL(\n        FORMAT_TIME(\"%H:%M:%E3S\", TIME_ADD(TIME \"00:00:00\", INTERVAL CAST((tests.duration * 1000) AS INT64) MILLISECOND)),\n        \"\"\n    ) AS duration_str,\n    (CASE status WHEN \"ERROR\" THEN 5 WHEN \"FAIL\" THEN 4 WHEN \"PASS\" THEN 3 WHEN \"DONE\" THEN 2 WHEN \"SKIP\" THEN 1 ELSE 0 END) -\n        (CASE waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6 AS status_num\nFROM ${dataset}.tests\nINNER JOIN\n    ${dataset}.builds AS builds\n    ON\n        tests.build_id = builds.id AND\n        builds.checkout_id = ${id:json} AND\n        IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n        IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nWHERE\n    IFNULL(tests.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to), TRUE) AND\n    tests.origin LIKE ${origin} AND\n    (${test_path:json} = \"\" OR tests.path = ${test_path:json} OR STARTS_WITH(tests.path, ${test_path:json} || \".\"))\nORDER BY\n    status_num DESC,\n    tests.path ASC"
    }
   ]
  }
 ]
}