{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "origin",
    "label": "Origin",
    "query": "SELECT DISTINCT origin FROM ${dataset}.checkouts"
   },
   { "name": "dataset", "query": "kcidb_sample" },
   {
    "name": "build_architecture",
    "label": "Build architecture",
    "query": "SELECT DISTINCT architecture FROM ${dataset}.builds"
   },
   {
    "name": "build_config_name",
    "label": "Build configuration",
    "query": "SELECT DISTINCT config_name FROM ${dataset}.builds"
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "Welcome to Linux Kernel CI report database (**KCIDB**) dashboard.\nHere you can find testing reports aggregated from multiple CI systems (\"**origins**\"), sent in the past month.\nThis is a work in progress, and we welcome contributions and participation.\nSee the source code for [the collection system][kcidb], and for [this dashboard][kcidb-grafana].\nWrite to [kernelci@lists.linux.dev][maillist] if you want to start submitting results from your CI system,\nor if you want to receive customized notifications of arriving results.\n\n[kcidb]: https://github.com/kernelci/kcidb/\n[kcidb-grafana]: https://github.com/kernelci/kcidb-grafana/\n[maillist]: mailto:kernelci@lists.linux.dev"
  },
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "/* Massage */\nSELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    git_repository_url,\n    IF(git_repository_branches IS NULL,\n       \"\",\n       IF(ARRAY_LENGTH(git_repository_branches) <= 3,\n          ARRAY_TO_STRING(git_repository_branches, \", \"),\n          (SELECT CONCAT(STRING_AGG(branch, \", \"), \" (+\", (ARRAY_LENGTH(git_repository_branches) - 3), \")\")\n           FROM (SELECT branch FROM UNNEST(git_repository_branches) AS branch ORDER BY branch DESC LIMIT 3)\n          )\n       )\n    ) AS git_repository_branches_string,\n    checkouts\nFROM (\n    /* Aggregate */\n    SELECT git_repository_url, git_repository_branches, checkouts\n    FROM (\n        SELECT DISTINCT git_repository_url\n        FROM ${dataset}.checkouts\n        WHERE git_repository_url IS NOT NULL\n    )\n    LEFT OUTER JOIN (\n        SELECT\n            git_repository_url,\n            ARRAY_AGG(DISTINCT git_repository_branch) AS git_repository_branches,\n            COUNT(id) AS checkouts\n        FROM ${dataset}.checkouts\n        WHERE IFNULL(start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND origin LIKE ${origin}, TRUE)\n        GROUP BY git_repository_url\n    ) USING(git_repository_url)\n)\nORDER BY checkouts DESC, git_repository_url ASC"
    }
   ]
  },
  {
   "title": "Test nodes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "/* Massage */\nSELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    origins,\n    path,\n    architectures,\n    tests,\n    status_num\nFROM (\n    /* Aggregate */\n    SELECT\n        STRING_AGG(DISTINCT origin, \", \") AS origins,\n        LEFT(base_prefix, CHAR_LENGTH(base_prefix) - 1) AS path,\n        STRING_AGG(DISTINCT architecture, \", \") AS architectures,\n        COUNT(DISTINCT id) AS tests,\n        MAX((CASE status WHEN \"ERROR\" THEN 5 WHEN \"FAIL\" THEN 4 WHEN \"PASS\" THEN 3 WHEN \"DONE\" THEN 2 WHEN \"SKIP\" THEN 1 ELSE 0 END) -\n            (CASE waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6) AS status_num\n    FROM (\n        /* Filter tests and extract path prefixes */\n        SELECT\n            tests.origin,\n            tests.id,\n            /* Prefix one level deeper than the displayed test's path */\n            IFNULL(\n                NULLIF(\n                    /* Cut the test path up to and including the first dot */\n                    LEFT(tests.path, INSTR(tests.path, \".\", 2)),\n                    \"\"\n                ),\n                tests.path || \".\"\n            ) AS base_prefix,\n            builds.architecture,\n            tests.status AS status,\n            tests.waived AS waived\n        FROM ${dataset}.tests\n        INNER JOIN\n            ${dataset}.builds AS builds\n            ON\n                tests.build_id = builds.id AND\n                IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n                IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\n        WHERE\n            tests.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to) AND\n            tests.origin LIKE ${origin} AND\n            tests.path IS NOT NULL AND\n            tests.path != \"\"\n    )\n    GROUP BY\n        base_prefix\n)\nORDER BY\n    tests DESC,\n    path ASC"
    }
   ]
  },
  {
   "title": "Revisions",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "/*\n * Truncate a string with an ellipsis at speсified length.\n */\nCREATE TEMP FUNCTION TRUNCATE(str STRING, len INT64)\n    RETURNS STRING\n    AS (IF(len = 0 OR CHAR_LENGTH(str) <= len,\n           str,\n           CONCAT(SUBSTR(str, 1, len - 1), \"…\")\n       ));\n\n/*\n * Replace NULL or empty string with a non-breaking space,\n * truncate anything else with ellipsis, if necessary.\n */\nCREATE TEMP FUNCTION BLANK_OR_TRUNCATE(str STRING, len INT64)\n    RETURNS STRING\n    AS (IF(str IS NULL OR str = \"\", \" \", TRUNCATE(str, len)));\n\n/*\n * Format an array of strings as a three-line text with ellipsis\n */\nCREATE TEMP FUNCTION ARRAY_TO_TEXT(strs ARRAY<STRING>, width INT64)\n    RETURNS STRING\n    AS (ARRAY_TO_STRING(\n        [\n            BLANK_OR_TRUNCATE(strs[SAFE_OFFSET(0)], width),\n            BLANK_OR_TRUNCATE(strs[SAFE_OFFSET(1)], width),\n            IF(ARRAY_LENGTH(strs) > 3, \"…\",\n               BLANK_OR_TRUNCATE(strs[SAFE_OFFSET(2)], width))\n        ],\n        \"\\n\"\n    ));\n\nWITH\n    filtered_checkouts AS (\n        SELECT\n            *\n        FROM\n            ${dataset}.checkouts\n        WHERE\n            origin LIKE ${origin} AND\n            IFNULL(checkouts.start_time BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to), TRUE)\n    ),\n    revision_sources AS (\n        SELECT\n            git_commit_hash,\n            patchset_hash,\n            ARRAY_TO_TEXT(\n                ARRAY_AGG(git_repository_url_str\n                          ORDER BY rank DESC, git_repository_url_str,\n                                   git_repository_branch_str, git_commit_name_str),\n                128\n            ) AS git_repository_urls_text,\n            ARRAY_TO_TEXT(\n                ARRAY_AGG(git_repository_branch_str\n                          ORDER BY rank DESC, git_repository_url_str,\n                                   git_repository_branch_str, git_commit_name_str),\n                32\n            ) AS git_repository_branches_text,\n            ARRAY_TO_TEXT(\n                ARRAY_AGG(git_commit_name_str\n                          ORDER BY rank DESC, git_repository_url_str,\n                                   git_repository_branch_str, git_commit_name_str),\n                32\n            ) AS git_commit_names_text,\n        FROM (\n            SELECT\n                git_commit_hash,\n                patchset_hash,\n                git_repository_url_str,\n                git_repository_branch_str,\n                git_commit_name_str,\n                IF(git_repository_url_str = \"\", 0, 4) +\n                    IF(git_repository_branch_str = \"\", 0, 2) +\n                    IF(git_commit_name_str = \"\", 0, 1) AS rank\n            FROM (\n                SELECT DISTINCT\n                    git_commit_hash,\n                    patchset_hash,\n                    IFNULL(git_repository_url, \"\") AS git_repository_url_str,\n                    IFNULL(git_repository_branch, \"\") AS git_repository_branch_str,\n                    IFNULL(git_commit_name, \"\") AS git_commit_name_str,\n                FROM\n                    filtered_checkouts\n            )\n        )\n        GROUP BY\n            git_commit_hash,\n            patchset_hash\n    )\n/* Massage and join with sources */\nSELECT\n    IF(${origin} = \"%\", \"All\", ${origin}) AS origin_param,\n    IF(${build_architecture} = \"%\", \"All\", ${build_architecture}) AS build_architecture_param,\n    IF(${build_config_name} = \"%\", \"All\", ${build_config_name}) AS build_config_name_param,\n    revisions.git_commit_hash,\n    revisions.patchset_hash,\n    origins_str,\n    SUBSTR(revisions.git_commit_hash, 0, 12) AS git_commit_hash_short,\n    revision_sources.git_repository_urls_text,\n    revision_sources.git_repository_branches_text,\n    revision_sources.git_commit_names_text,\n    SUBSTR(revisions.patchset_hash, 0, 12) AS patchset_hash_short,\n    IFNULL(CAST(checkouts_start_time AS STRING), \"\") AS checkouts_start_time_str,\n    checkouts_valid_num,\n    builds_valid_num,\n    tests_status_num\nFROM (\n    /* Calculate revision statuses */\n    SELECT\n        checkouts.git_commit_hash,\n        checkouts.patchset_hash,\n        STRING_AGG(DISTINCT checkouts.origin, \", \") AS origins_str,\n        MIN(checkouts.start_time) AS checkouts_start_time,\n        MAX(CASE checkouts.valid WHEN false THEN 1 WHEN true THEN 0 ELSE -1 END) AS checkouts_valid_num,\n        MAX(CASE builds.valid WHEN false THEN 1 WHEN true THEN 0 ELSE -1 END) AS builds_valid_num,\n        MAX((CASE tests.status WHEN \"ERROR\" THEN 5 WHEN \"FAIL\" THEN 4 WHEN \"PASS\" THEN 3 WHEN \"DONE\" THEN 2 WHEN \"SKIP\" THEN 1 ELSE 0 END) -\n            (CASE tests.waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6) AS tests_status_num\n    FROM\n        filtered_checkouts AS checkouts\n    LEFT OUTER JOIN\n        ${dataset}.builds AS builds\n        ON\n            builds.checkout_id = checkouts.id AND\n            IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n            IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\n    LEFT OUTER JOIN\n        ${dataset}.tests AS tests\n        ON\n            tests.build_id = builds.id\n    GROUP BY\n        checkouts.git_commit_hash,\n        checkouts.patchset_hash\n) AS revisions\nINNER JOIN\n    revision_sources\n    ON\n        revision_sources.git_commit_hash = revisions.git_commit_hash AND\n        revision_sources.patchset_hash = revisions.patchset_hash\nORDER BY\n    checkouts_start_time DESC"
    }
   ]
  },
  {
   "title": "Build status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n)\nSELECT\n    interval_start AS time,\n    CASE builds.valid WHEN true THEN \"PASS\" WHEN false THEN \"FAIL\" ELSE \"UNKNOWN\" END AS metric,\n    COUNT(DISTINCT builds.id) AS builds\nFROM ${dataset}.builds AS builds\nINNER JOIN intervals ON builds.start_time >= interval_start AND builds.start_time < interval_end\nWHERE\n  builds.origin LIKE ${origin} AND\n  IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n  IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nGROUP BY time, metric\nORDER BY time ASC, metric ASC"
    }
   ]
  },
  {
   "title": "Test status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n)\nSELECT\n  interval_start AS time,\n  IFNULL(tests.status, \"UNKNOWN\") AS metric,\n  COUNT(DISTINCT tests.id) AS tests\nFROM\n  ${dataset}.builds AS builds, ${dataset}.tests AS tests\nINNER JOIN intervals ON tests.start_time >= interval_start AND tests.start_time < interval_end\nWHERE\n  builds.id = tests.build_id AND\n  tests.origin LIKE ${origin} AND\n  IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n  IFNULL(builds.config_name LIKE ${build_config_name}, TRUE)\nGROUP BY\n  time, metric\nORDER BY\n  time ASC, metric ASC"
    }
   ]
  },
  {
   "title": "Reports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n), filtered_checkouts AS (\n    SELECT\n        checkouts.id AS id,\n        checkouts.origin AS origin,\n        checkouts.start_time AS time\n    FROM\n        ${dataset}.checkouts AS checkouts\n    WHERE\n    \tcheckouts.start_time BETWEEN TIMESTAMP_MILLIS ($__from) AND TIMESTAMP_MILLIS ($__to)\n), filtered_builds AS (\n    SELECT\n        builds.id AS id,\n        builds.origin AS origin,\n        builds.start_time AS time\n    FROM\n        ${dataset}.builds AS builds,\n        filtered_checkouts\n    WHERE\n    \tbuilds.start_time BETWEEN TIMESTAMP_MILLIS ($__from) AND TIMESTAMP_MILLIS ($__to) AND\n        IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n        IFNULL(builds.config_name LIKE ${build_config_name}, TRUE) AND\n        filtered_checkouts.id = builds.checkout_id\n), filtered_tests AS (\n    SELECT\n        tests.id AS id,\n        tests.origin AS origin,\n        tests.start_time AS time\n    FROM\n        ${dataset}.tests AS tests,\n        filtered_builds\n    WHERE\n    \ttests.start_time BETWEEN TIMESTAMP_MILLIS ($__from) AND TIMESTAMP_MILLIS ($__to) AND\n        filtered_builds.id = tests.build_id\n)\nSELECT\n    interval_start AS time,\n    counted_checkouts.count AS Checkouts,\n    counted_builds.count AS Builds,\n    counted_tests.count AS Tests\nFROM intervals\nLEFT OUTER JOIN (\n    SELECT interval_start, COUNT(id) AS count,\n    FROM filtered_checkouts\n    INNER JOIN intervals ON time >= interval_start AND time < interval_end\n    WHERE origin LIKE ${origin}\n    GROUP BY interval_start\n) AS counted_checkouts USING(interval_start)\nLEFT OUTER JOIN (\n    SELECT interval_start, COUNT(id) AS count,\n    FROM filtered_builds\n    INNER JOIN intervals ON time >= interval_start AND time < interval_end\n    WHERE origin LIKE ${origin}\n    GROUP BY interval_start\n) AS counted_builds USING(interval_start)\nLEFT OUTER JOIN (\n    SELECT interval_start, COUNT(id) AS count,\n    FROM filtered_tests\n    INNER JOIN intervals ON time >= interval_start AND time < interval_end\n    WHERE origin LIKE ${origin}\n    GROUP BY interval_start\n) AS counted_tests USING(interval_start)"
    }
   ]
  },
  {
   "title": "Builds per architecture",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "kcidb_sample",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "kernelci",
     "rawSql": "WITH intervals AS (\n    SELECT\n        interval_start,\n        TIMESTAMP_ADD(interval_start, INTERVAL $__interval_ms*50 MILLISECOND) AS interval_end\n    FROM UNNEST(\n        GENERATE_TIMESTAMP_ARRAY(TIMESTAMP_MILLIS($__from),\n                                 TIMESTAMP_MILLIS($__to),\n                                 INTERVAL $__interval_ms*50 MILLISECOND)\n    ) AS interval_start\n)\nSELECT\n  interval_start AS time,\n  builds.architecture AS metric,\n  COUNT(DISTINCT builds.id) AS Builds\nFROM\n  ${dataset}.builds AS builds\nJOIN intervals ON start_time >= interval_start AND start_time < interval_end\nWHERE\n  builds.origin LIKE ${origin} AND\n  IFNULL(builds.architecture LIKE ${build_architecture}, TRUE) AND\n  IFNULL(builds.config_name LIKE ${build_config_name}, TRUE) AND\n  builds.start_time BETWEEN TIMESTAMP_MILLIS(${__from}) AND TIMESTAMP_MILLIS(${__to})\nGROUP BY\n  time, metric\nORDER BY\n  time ASC, metric ASC"
    }
   ]
  }
 ]
}