{
 "title": "Revision",
 "time": { "from": "now-100y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin",
    "label": "Origin",
    "query": "SELECT DISTINCT revision_origin FROM ${dataset}.builds"
   },
   {
    "name": "origin_id",
    "label": "Origin ID",
    "query": "https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git@767d3ded5fb88e95f137893a8d90d1738b897029"
   },
   { "name": "dataset", "query": "kernelci02" }
  ]
 },
 "panels": [
  {
   "title": "Origin",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Repo",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  origin,\n  origin_id,\n  git_repository_url,\n  git_repository_branch,\n  git_repository_commit_name,\n  git_repository_commit_hash,\n  CASE revisions.valid WHEN true THEN 1 WHEN false THEN 0 ELSE -1 END AS valid_num,\n  description,\n  IF(discovery_time IS NULL, \"\", CAST(discovery_time AS STRING)) AS discovery_time_str,\n  log_url,\n  misc\nFROM ${dataset}.revisions WHERE origin=\"${origin}\" AND origin_id=\"${origin_id}\" ORDER BY discovery_time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Builds",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Tests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Branch",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Hash",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Description",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Discovery Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Log",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Builds",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  builds.origin,\n  builds.origin_id,\n  builds.description,\n  builds.architecture,\n  builds.config_name,\n  IF(builds.start_time is NULL, \"\", CAST(builds.start_time AS STRING)) as builds_start_time_str,\n  IF(builds.duration is NULL, \"\", FORMAT_TIME(\"%H:%M:%E3S\", TIME_ADD(TIME \"00:00:00\", INTERVAL CAST((builds.duration * 1000) AS INT64) MILLISECOND))) as duration_str,\n  CASE builds.valid WHEN true THEN 1 WHEN false THEN 0 ELSE -1 END AS builds_valid_num,\n  MAX((CASE tests.status WHEN \"SKIP\" THEN 1 WHEN \"DONE\" THEN 2 WHEN \"PASS\" THEN 3 WHEN \"FAIL\" THEN 4 WHEN \"ERROR\" THEN 5 ELSE 0 END) -\n      (CASE tests.waived WHEN false THEN 0 WHEN true THEN 1 ELSE 2 END) * 6) as tests_status_num\nFROM ${dataset}.builds AS builds\nLEFT OUTER JOIN ${dataset}.tests AS tests ON tests.build_origin = builds.origin AND tests.build_origin_id = builds.origin_id\nWHERE\n  revision_origin = \"$origin\" AND\n  revision_origin_id = \"$origin_id\" AND\n  (\n    builds.start_time >= TIMESTAMP_MILLIS(${__from}) AND builds.start_time <= TIMESTAMP_MILLIS(${__to}) OR\n    builds.start_time IS NULL\n  )\nGROUP BY\n  builds.origin,\n  builds.origin_id,\n  builds.description,\n  builds.architecture,\n  builds.config_name,\n  builds.start_time,\n  builds.duration,\n  builds.valid\nORDER BY builds.start_time ASC"
    }
   ]
  },
  {
   "title": "Patches",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "orderByCol": "2",
     "orderBySort": "1",
     "rawSql": "SELECT *\nFROM UNNEST((\n  SELECT patch_mboxes\n  FROM kernelci02.revisions\n  WHERE origin = \"${origin}\" AND origin_id = \"${origin_id}\"\n  ORDER BY discovery_time DESC\n  LIMIT 1\n))\nWITH OFFSET as idx\nORDER BY idx ASC"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "panelId": 6 }
   ]
  }
 ]
}